name: continuous integration example

on:
  push:
    branches: # run this whenever pushed to main branch
      main

jobs:
  build-and-test-please:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1 #checks out main branch and puts into virtual machine

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: "11"

      - name: Build with gradle!
        working-directory: . # make sure to change for Tartan path
        run: | # "piping", running two commands right after the other
          chmod +x gradlew
          ./gradlew build -x test

      - name: Run tests!!!
        working-directory: .
        run: | 
          chmod +x gradlew
          ./gradlew test
          
